name: AllSigns
main: surva\allsigns\AllSigns
version: 1.0.12
api: 3.0.0

author: survanetwork
description: Turn signs into world teleport and command signs
website: https://github.com/survanetwork/AllSigns
